#!/usr/bin/env bash
# The documentation cites the scripts. Nothing checked that the citations were
# true, and they rotted: CONTRIBUTING.md pointed at git_sync_default.sh:25-33
# for a function that had moved to 27, at stay_fresh.sh:357-405 for one that had
# moved to 499, and at windows/README.md:29-31 for a rule that was no longer in
# that file at all. Every one of those was written accurately and went stale
# underneath, because a line number does not survive an edit above it.
#
# So this checks what can be checked mechanically:
#
#   1. no line-number citations at all — they are the format that rots
#   2. every relative link resolves
#   3. every in-page anchor a document links to is generated by a heading in it
#   4. every "`fn()` in `path`" citation resolves to a function in that file
#   5. every package README names the scripts beside it, and documents no
#      script that is not there
#
# What is deliberately NOT checked: a bare `name.sh` written in prose. The
# first draft did check those and flagged `formulae.brew.sh` (a hostname) and
# a README's own note that v1_stay_fresh.sh was "formerly old_stay_fresh.sh".
# Both are correct prose. A check that has to grow an exemption list for
# correct writing is the check people switch off, so this one stays on the
# three forms that are unambiguous claims about the tree.
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$HERE/../.." && pwd)}"
cd "$REPO_ROOT" || { echo "cannot enter $REPO_ROOT" >&2; exit 1; }

failures=0
ok()   { printf '[ ok ] %s\n' "$*"; }
err()  { printf '[fail] %s\n' "$*" >&2; failures=$((failures + 1)); }
head_() { printf '\n--- %s ---\n' "$*"; }

docs=()
while IFS= read -r f; do docs+=("$f"); done < <(git ls-files '*.md')

# --------------------------------------------------------------------------
head_ "no line-number citations"
# CHANGELOG.md is history: an entry describing a bug at the line it lived on
# stays true of the commit it describes, so it is exempt rather than rewritten.
found=0
for f in "${docs[@]}"; do
  case "$f" in CHANGELOG.md) continue ;; esac
  hits="$(grep -noE '`[A-Za-z0-9_./-]+\.(sh|py|ps1|psd1|lua|yml|yaml):[0-9]+(-[0-9]+)?`' "$f")"
  if [[ -n "$hits" ]]; then
    err "$f cites a line number; cite the function or the file instead"
    printf '%s\n' "$hits" | sed 's/^/       /' >&2
    found=$((found + 1))
  fi
done
(( found == 0 )) && ok "no document cites a line number"

# --------------------------------------------------------------------------
head_ "relative links resolve"
# markdownlint does not check link targets. docs/good-first-issues.md was
# deleted while README.md and CONTRIBUTING.md still linked to it, and the lint
# job passed.
broken=0
for f in "${docs[@]}"; do
  while IFS= read -r target; do
    [[ -n "$target" ]] || continue
    case "$target" in http://*|https://*|mailto:*|'#'*) continue ;; esac
    path="${target%%#*}"
    [[ -n "$path" ]] || continue
    if [[ ! -e "$(dirname "$f")/$path" ]]; then
      err "$f links to $path, which does not exist"
      broken=$((broken + 1))
    fi
  # Inline code spans are blanked first: a document that quotes `](../other.md)`
  # as an example of link syntax is describing a link, not making one, and
  # GitHub renders it as literal text. See strip_code() further down.
  done < <(sed 's/`[^`]*`/ /g' "$f" | grep -hoE '\]\([^)]+\)' | sed 's/^](//; s/)$//')
done
(( broken == 0 )) && ok "every relative link in a document resolves"

# --------------------------------------------------------------------------
head_ "in-page anchors resolve"
# A Contents list is a set of claims about the headings under it, and nothing
# checked them: the section above throws the fragment away and asks only about
# the path, so a README whose `](#winget_bootstrapps1)` was replaced with
# `](#this-anchor-does-not-exist)` still passed this suite. A dead anchor does
# not render as a dead link either — it renders as an ordinary link that
# scrolls nowhere — so nobody finds it by reading. The documents here carry
# Contents lists built from generated slugs, and renaming one heading orphans
# every link to it in silence.
#
# The slug rule is the one GitHub applies (github-slugger): take the heading
# text, lowercase it, DELETE every character that is not a letter, a digit, an
# underscore, a space or a hyphen, then turn each remaining space into a
# hyphen. Deleting rather than replacing is the part that surprises people,
# and the documents here depend on it in both directions:
#
#   ## winget_bootstrap.ps1          -> #winget_bootstrapps1
#   ## What's in `.aliases`          -> #whats-in-aliases
#   ## Kali red/blue lab cloud-init  -> #kali-redblue-lab-cloud-init
#   ## Development: Docker checks    -> #development-docker-checks
#
# The last pair is the one to keep in mind: a deleted character leaves the
# spaces around it behind, so `A: B` slugs to #a-b with one hyphen while
# `A & B` slugs to #a--b with two.
#
# Headings inside a fenced code block are not headings. Dozens of lines here
# open with a # inside a ``` block — shell comments in usage examples — and
# counting them would mint anchors GitHub never generates, which is how a link
# checker comes to report a pass for a link that is dead. Both halves of the
# comparison come out of the same fence-aware pass for that reason.
#
# A repeated heading takes GitHub's -1, -2 suffixes in document order, which
# CHANGELOG.md needs: it carries one `### Added` per release.
#
# The fragment on a link into another document — the `](../README.md#section)`
# form — is checked by the section below this one, against the same slug rule
# resolved in the target file. It was split out because widening the check and
# repairing the four links it first flagged were two different reviews; the
# repairs landed, so both halves run now.
#
# Interval expressions ({1,6}) are avoided throughout: the awk that ships on
# older macOS does not implement them and matches them literally, which would
# make this collect nothing and say so only because of the floor below.
anchor_awk='
# A link inside a backtick span is a code sample, not a link: GitHub renders
# `](#anchor)` as literal text. Documentation that explains link syntax - the
# changelog fragments describing this very check, for one - would otherwise be
# reported as carrying dead links, and a checker that flags its own
# documentation is a checker people learn to work around. Spans are blanked
# rather than deleted so offsets the caller may rely on do not shift.
function strip_code(line,   out, i, n, inside, c) {
  out = ""
  n = length(line)
  inside = 0
  for (i = 1; i <= n; i++) {
    c = substr(line, i, 1)
    if (c == "`") { inside = !inside; out = out " "; continue }
    out = out (inside ? " " : c)
  }
  return out
}
function slug(text,   s) {
  s = tolower(text)
  gsub(/[^a-z0-9 _-]/, "", s)
  gsub(/ /, "-", s)
  return s
}
FNR == 1 { fence = "" }
/^[ \t]*(```|~~~)/ {
  if (fence == "") { fence = ($0 ~ /~~~/) ? "~~~" : "```" }
  else if (index($0, fence) > 0) { fence = "" }
  next
}
fence != "" { next }
mode == "headings" && /^ ? ? ?#/ {
  text = $0
  sub(/^ +/, "", text)
  if (!match(text, /^#+/)) next
  level = RLENGTH
  if (level > 6) next
  text = substr(text, level + 1)
  # `#hashtag` is not a heading; `##` alone is one, with no text.
  if (text != "" && text !~ /^[ \t]/) next
  sub(/^[ \t]+/, "", text)
  sub(/[ \t]+#+[ \t]*$/, "", text)
  sub(/[ \t]+$/, "", text)
  # A link in a heading anchors on its text, not on its target. No heading
  # here has one today; the line is what stops the first one from reading as
  # a broken anchor.
  gsub(/\]\([^)]*\)/, "]", text)
  base = slug(text)
  if (base == "") next
  s = base
  while ((FILENAME SUBSEP s) in taken) {
    taken[FILENAME SUBSEP base]++
    s = base "-" taken[FILENAME SUBSEP base]
  }
  taken[FILENAME SUBSEP s] = 0
  print s
}
mode == "links" {
  s = strip_code($0)
  # RSTART and RLENGTH are globals: copy both before doing anything else with
  # the match, or the scan advances by some later match offsets and a line
  # with two links is rescanned from the wrong place.
  while (match(s, /\]\(#[^)]*\)/)) {
    start = RSTART; len = RLENGTH
    if (len <= 0) break
    if (len > 4) print substr(s, start + 3, len - 4)
    s = substr(s, start + len)
  }
}
'

bad_anchor=0
headings_seen=0
anchors_checked=0
for f in "${docs[@]}"; do
  slugs="$(awk -v mode=headings "$anchor_awk" "$f")"
  if [[ -n "$slugs" ]]; then
    headings_seen=$((headings_seen + $(printf '%s\n' "$slugs" | wc -l | tr -d ' ')))
  fi
  while IFS= read -r target; do
    [[ -n "$target" ]] || continue
    anchors_checked=$((anchors_checked + 1))
    # A here-string, not a pipe into grep -q. grep -q exits at the first match
    # and would kill the writer with SIGPIPE; under `set -o pipefail` the
    # pipeline then reports 141 and every hit reads as a miss. This repository
    # has paid for that shape three times.
    if ! grep -qxF "$target" <<<"$slugs"; then
      err "$f links to #$target, which no heading in it generates"
      bad_anchor=$((bad_anchor + 1))
    fi
  done < <(awk -v mode=links "$anchor_awk" "$f")
done

if (( headings_seen == 0 || anchors_checked == 0 )); then
  err "collected $headings_seen heading(s) and $anchors_checked in-page link(s) — this check has stopped checking"
elif (( bad_anchor == 0 )); then
  ok "every in-page anchor resolves ($anchors_checked link(s) against $headings_seen heading(s))"
fi

# --------------------------------------------------------------------------
head_ "function citations resolve"
# The form CONTRIBUTING.md uses now: `run_cmd()` in `macos-initial-setup/stay_fresh.sh`.
bad_fn=0
checked_fn=0
for f in "${docs[@]}"; do
  while IFS= read -r line; do
    fn="${line%%|*}"
    path="${line##*|}"
    [[ -n "$fn" && -n "$path" ]] || continue
    if [[ ! -f "$path" ]]; then
      err "$f cites $fn() in $path, which is not a file"
      bad_fn=$((bad_fn + 1))
      continue
    fi
    checked_fn=$((checked_fn + 1))
    if ! grep -qE "^[[:space:]]*(function )?${fn}\(\)[[:space:]]*\{" "$path"; then
      err "$f cites $fn() in $path, which does not define it"
      bad_fn=$((bad_fn + 1))
    fi
  done < <(grep -hoE '`[a-z_][a-z0-9_]*\(\)` in `[A-Za-z0-9_./-]+\.(sh|py)`' "$f" \
             | sed 's/`//g; s/() in /|/')
done
if (( checked_fn == 0 )); then
  ok "no function citations to check"
elif (( bad_fn == 0 )); then
  ok "all $checked_fn function citations resolve"
fi

# --------------------------------------------------------------------------
head_ "cross-file anchors resolve"
# The other half of the link above: `](../macos-initial-setup/README.md#a-b)`
# names a file AND a heading inside it. The relative-link section checks the
# path and throws the fragment away; the in-page section checks fragments but
# only against the file they sit in. Between them a link could name a real file
# and a heading that file does not have, which is exactly what four links here
# did — three spelled `#development--docker-checks` with the two hyphens of an
# older `&`-era title after the heading became `## Development: Docker checks`,
# and one pointed at `#testing-docker` where the root README says `## Testing`.
# They rendered as ordinary links that scroll nowhere, so reading never found
# them; each was written correctly and went stale underneath.
#
# Only .md targets are resolved. A fragment on a link to a script or a
# directory is not a heading reference and is left alone.
cross_checked=0
bad_cross=0
while IFS= read -r f; do
  [[ -n "$f" ]] || continue
  while IFS= read -r pair; do
    [[ -n "$pair" ]] || continue
    rel="${pair%%|*}"
    frag="${pair##*|}"
    [[ -n "$rel" && -n "$frag" ]] || continue
    case "$rel" in *.md) ;; *) continue ;; esac
    target="$(cd "$(dirname "$f")" 2>/dev/null && cd "$(dirname "$rel")" 2>/dev/null && pwd)/$(basename "$rel")"
    # The path half is already this suite's business one section up; a missing
    # file is reported there, so here it is only a reason to stop.
    [[ -f "$target" ]] || continue
    cross_checked=$((cross_checked + 1))
    target_slugs="$(awk -v mode=headings "$anchor_awk" "$target")"
    # Here-string, not a pipe: see the note on SIGPIPE in the section above.
    if ! grep -qxF "$frag" <<<"$target_slugs"; then
      err "$f links to $rel#$frag, which no heading in that file generates"
      bad_cross=$((bad_cross + 1))
    fi
  # Same reasoning as strip_code() above: blank inline code spans first, so a
  # fragment that quotes `](../other.md#section)` as an example is not read as
  # a link to a file called other.md.
  done < <(sed 's/`[^`]*`/ /g' "$f" \
             | grep -hoE '\]\([^)#]+\.md#[^)]+\)' \
             | sed 's/^](//; s/)$//; s/#/|/')
done < <(git ls-files '*.md')
if (( cross_checked == 0 )); then
  err "collected 0 cross-file anchor(s) — this check has stopped checking"
elif (( bad_cross == 0 )); then
  ok "every cross-file anchor resolves ($cross_checked link(s))"
fi

head_ "package READMEs name their scripts"
# Both directions, because both have failed here. Forward: mikrotik once took a
# batch of twelve scripts with no README entry, which is why that package grew
# its own drift check. Reverse: a heading for a script somebody deleted outlives
# the script, and markdownlint has no opinion about it.
#
# A script belongs to the NEAREST README above it, not to every README above it.
# The first draft used `git ls-files "$pkg/*.sh"`, and git pathspec globs cross
# directory boundaries: windows/README.md was silently held to naming the eight
# scripts under windows/setup/ and windows/wsl/, each was counted twice, and
# both error messages named the wrong directory.
#
# Packages are discovered, not listed. The macOS suite's hardcoded script list
# is how launchd/stay_fresh_agent.sh stopped being covered. test-env/ is
# excluded wholesale, the same rule discover_clis.sh uses; so is the repository
# root, whose README is an index of packages rather than a package README.
readmes="$(mktemp)"; mentions="$(mktemp)"
trap 'rm -f "$readmes" "$mentions"' EXIT
# The pathspec is a glob over the whole path, so '*README.md' also matches
# LEGACY_README.md and DESIGN_README.md. The first invented a second entry for
# a package that already had one (orphan headings reported twice) and the
# second invented a package whose README.md does not exist, so the reverse loop
# grepped a missing file. Match the basename exactly.
git ls-files '*README.md' | while IFS= read -r r; do
  [ "${r##*/}" = "README.md" ] || continue
  d="$(dirname "$r")"
  case "$d" in .|test-env|test-env/*) continue ;; esac
  printf '%s\n' "$d"
done > "$readmes"

fwd_missing=0
rev_missing=0
scripts_seen=0
pkgs="$(wc -l < "$readmes" | tr -d ' ')"

# Forward: every script is named in the README of its nearest package.
while IFS= read -r f; do
  case "$f" in */tests/*|test-env/*|run-tests.sh) continue ;; esac
  owner=""
  d="$(dirname "$f")"
  while [ "$d" != "." ] && [ -n "$d" ]; do
    if grep -qxF "$d" "$readmes"; then owner="$d"; break; fi
    d="$(dirname "$d")"
  done
  # Skipping this silently was the largest hole: a brand-new package, or one
  # whose README was deleted, took its scripts out of coverage and left the
  # suite green. Every shipped script lives in a package that documents it.
  if [ -z "$owner" ]; then
    err "$f has no package README above it; add one, or move the script into a package"
    fwd_missing=$((fwd_missing + 1))
    continue
  fi
  scripts_seen=$((scripts_seen + 1))
  base="${f##*/}"
  # Whole-token match at both ends. Without the left boundary the class
  # provides, `v1_stay_fresh.sh` in the prose counts as `stay_fresh.sh`;
  # without the right one, prose about `deploy.shtml` counts as `deploy.sh`.
  # The trailing boundary character, when there is one, is then stripped.
  grep -oE '[A-Za-z0-9_./-]+\.(sh|py|lua|ps1)([^A-Za-z0-9_]|$)' "$owner/README.md" \
    | sed 's/[^A-Za-z0-9]$//; s#.*/##' | sort -u > "$mentions"
  # -F, because the filename is data: an undocumented `bash.aliases.sh` used as
  # a pattern matches the documented `bash_aliases.sh`.
  grep -qxF "$base" "$mentions" && continue
  err "$owner/README.md does not mention $base, which ships beside it"
  fwd_missing=$((fwd_missing + 1))
done < <(git ls-files '*.sh' '*.py' '*.lua' '*.ps1')

# Reverse: a heading naming a script is a claim that the script is there. The
# name may carry a path — `## `launchd/stay_fresh_agent.sh`` — so the pattern
# has to allow a slash. Leaving it out exempted the two scripts documented that
# way, one of them the file this block's own comment cites as the reason it
# exists. Run for every package README, including one whose scripts have all
# been deleted: that is precisely when a heading is left orphaned.
while IFS= read -r pkg; do
  while IFS= read -r named; do
    [ -n "$named" ] || continue
    [ -f "$pkg/$named" ] && continue
    err "$pkg/README.md has a section for $named, which is not in $pkg/"
    rev_missing=$((rev_missing + 1))
  done < <(grep -hoE '^#+ `[A-Za-z0-9_./-]+\.(sh|py|lua|ps1)`' "$pkg/README.md" \
             | sed 's/^#* *//; s/`//g')
done < "$readmes"

if (( pkgs == 0 || scripts_seen == 0 )); then
  err "discovered $pkgs package README(s) and $scripts_seen script(s) — this check has stopped checking"
else
  (( fwd_missing == 0 )) && ok "every script is named in its package README ($scripts_seen across $pkgs packages)"
  (( rev_missing == 0 )) && ok "every documented script section has a script"
fi

# --------------------------------------------------------------------------
printf '\n'
if (( failures > 0 )); then
  printf '%d documentation citation check(s) failed\n' "$failures" >&2
  exit 1
fi
printf '=== all documentation citation checks passed (%d documents) ===\n' "${#docs[@]}"
exit 0
